### PR TITLE
refactor(palette): introduce better copy button

### PR DESCRIPTION
**Pull request by andreasgrafen**
This adds Svelte in favour of reactive islands. The palette page now uses a Svelte-based button componant to handle the "Copy to Clipboard"-interaction.

This further resolves the icon issue mentioned in https://github.com/catppuccin/website/issues/48#issuecomment-2023113509_

### CODE REVIEW

**Comment by andreasgrafen** [comment]
This actually doesn#t need to point to the custom-icon branch; my bad!

**Comment by nullishamy** [comment]
Looks good! 

Not sure if it's just my display, but these icons look a little small:
image

Only other comment is that it would be nice to have a fade in/out for the tick. Not a blocker, just a small aesthetic improvement.

**Comment by andreasgrafen** [comment]
They are the same 12x12 size they currently have on the live-site. Tho I've just noticed that I screwed up the formatting when it comes to the font. That might cause it to look so drastically different.

**Comment by nullishamy** [comment]
Hmmm. Probably a high-dpi thing wrt the icons. Seems fine though, as most people won't have an issue.

**Review by sgoudham — APPROVED** [review]

**Pull request merged**
