### PR TITLE
Catppuccin YAWP – yet another website proposal

### PR DESCRIPTION
**Pull request by andreasgrafen**
So this is yet another website proposal..

This one is meant to be a baseline for future development hence it's not super feature rich. Regarding the tech-stack I've stepped away from Next.js in favor of Astro as this allows us to easily render static files for now. If we're looking into dynamic content in the future Astro allows us to easily import components from other frontend frameworks as well.

### CODE REVIEW

**Comment by sgoudham** [comment]
Absolutely amazing work @andreasgrafen, obviously this is a MVP but I think we just need to merge this and get the ball rolling that way (like how we did with `catppuccin/userstyles`)

We're gonna need your help here @nekowinston in configuring the DNS records for `catppuccin.com` 
I know some parts of this discussion are sensitive so we should take it offline and talk further 👍

**Comment by andreasgrafen** [comment]
I've just resolved the (for now) last open review comment.
Flavors on `/palette` can now be linked directly with `/palette#flavor-{flavorName}` and all headlines on `/contributing` can also reached via direct link (e.g. `/contributing#port-creation`)

**Review by backwardspy — APPROVED** [review]

**Review by backwardspy — APPROVED** [review]
"it looks nice" - pcgamer

**Review by backwardspy — APPROVED** [review]
"i like it" - ign

**Review by isabelroses — APPROVED** [review]
very cool

**Review by backwardspy — APPROVED** [review]
"get out of my house" - hammy

**Comment by andreasgrafen** [comment]
»We at the BBC approve this message!«
BBC, probably

**Review by sgoudham — APPROVED** [review]
lgtm

**Review by andreasgrafen — COMMENTED** [review]
> Pull request authors can’t approve their own pull request.

:baldkek:

**Pull request merged**
